# Generated by Django 2.0.6 on 2018-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20180616_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/albums'),
        ),
    ]
