# Generated by Django 2.0.6 on 2018-06-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_auto_20180617_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
