# Generated by Django 2.0.6 on 2018-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_album_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
