# Generated by Django 2.0.6 on 2018-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_album_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='track',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
