# Generated by Django 2.0.6 on 2018-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_auto_20180812_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('section_text', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='release_label',
            field=models.CharField(default='Rodriguez Lopez Productions', max_length=100),
        ),
    ]
