# Generated by Django 2.0.6 on 2018-12-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_auto_20181228_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebarinfo',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Side bar info'},
        ),
        migrations.AddField(
            model_name='sidebarinfo',
            name='section_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
