# Generated by Django 2.0.6 on 2018-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_auto_20181228_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarinfo',
            name='section_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
