# Generated by Django 2.0.6 on 2018-06-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20180616_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(blank=True, max_length=256, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
            ],
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name_plural': 'Personnel'},
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='credit',
        ),
        migrations.AddField(
            model_name='albumcredit',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Personnel'),
        ),
    ]
