# Generated by Django 2.0.6 on 2018-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20180616_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_slug',
            field=models.CharField(default='fixme', max_length=100),
            preserve_default=False,
        ),
    ]
