# Generated by Django 2.0.6 on 2018-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_tag_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='album_tags', to='albums.Tag'),
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='track_tags', to='albums.Tag'),
        ),
    ]
